# Generated by Django 2.1.5 on 2019-02-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent_name', models.CharField(blank=True, default='', max_length=250)),
                ('pacient_name', models.CharField(blank=True, default='', max_length=250)),
                ('therapy_field', models.CharField(blank=True, default='', max_length=250)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
