# Generated by Django 2.1.5 on 2019-02-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='pacient_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='phone_number',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='time_preference',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='pacient_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='parent_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='therapy_field',
            field=models.CharField(default='', max_length=250),
        ),
    ]
